!> @brief
!>  This subroutine reads a file to provide values to re-start the run.
!>
!> @details
!>  This subroutine reads a summary file generated by a previous run 
!!  which provides all the tree information for all the GP individuals. The
!!  information read replaces the information usually generated by GP_Tree_Build
!!  and other routines on the first GP generation.
!>
!> @author Dr. John R. Moisan [NASA/GSFC]
!> @date January, 2013 Dr. John R. Moisan
!>
!> @param[in] i_GP_generation

SUBROUTINE read_all_summary_file( i_GP_generation )

 
!---------------------------------------------------------------------------  
!
! DESCRIPTION: 
! Brief description of routine. 

!
! REVISION HISTORY:
! TODO_dd_mmm_yyyy - TODO_describe_appropriate_changes - TODO_name
!
!---------------------------------------------------------------------------  

! program written by: Dr. John R. Moisan [NASA/GSFC] 31 January, 2013

!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
! if a restart is requested,
! read a summary file from a previous run and set the starting trees
! to the values in the file
!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

USE kinds_mod

USE mpi
USE mpi_module

USE GP_Parameters_module
USE GA_Parameters_module
USE GP_Variables_module
USE GA_Variables_module
USE GP_Data_module
USE GP_variables_module

IMPLICIT none

INTEGER (KIND=i4b) :: i_code_eq
INTEGER (KIND=i4b) :: istat

INTEGER (KIND=i4b),INTENT(IN)  :: i_GP_Generation
INTEGER (KIND=i4b)             :: i_GP_Gen
INTEGER (KIND=i4b)             :: i_GP_indiv

INTEGER (KIND=i4b) :: i_Tree
INTEGER (KIND=i4b) :: i_Node

LOGICAL :: Lprint

CHARACTER (200) :: Aline

!-------------------------------------------------------------------------------


!---------------------------------------------------
! assume this subroutine is called by all processes. W.J noted
!---------------------------------------------------

GP_Population_Initial_Conditions = 0.0d0
GP_Adult_Population_Node_Type    = -9999
GP_population_node_parameters    = 0.0d0

!-------------------------------------------------------------------------------

OPEN ( GP_restart_file_input_unit, file='GP_restart_file', &
      form = 'formatted', access = 'sequential', &
      status = 'old' )


! set Lprint so printing is done only under the conditions in the if-test

Lprint = .FALSE.

IF ( i_GP_generation == 1                                  .or. &
    MOD ( i_GP_generation, GP_child_print_interval ) == 0  .or. &
    i_GP_generation == n_GP_generations                          ) THEN
    Lprint = .TRUE.
END IF ! i_GP_generation == 1 .or. ...

!-------------------------------------------------------------------------------

readloop:&
DO 

    ! read the summary file header for each individual
    ! which has n_GP_parameters >= n_code_equations


    READ (GP_restart_file_input_unit, *, IOSTAT=istat) &
         i_GP_Gen, i_GP_indiv, &
         n_code_equations, n_trees, n_nodes, n_levels,  &
         GP_Adult_Population_SSE(i_GP_indiv)

    IF ( istat /= 0 ) exit readloop


    !---------------------------------------------------------------------------

    ! read initial conditions

    DO 

        READ (GP_restart_file_input_unit, '(A)', IOSTAT=istat) Aline

        IF ( istat /= 0 ) THEN
            exit readloop
        END IF ! istat /=0


        IF ( Aline(1:2) == '> '   ) exit

        READ (Aline, *)&
             i_GP_Gen, i_GP_indiv, i_code_eq, &
             GP_Population_Initial_Conditions( i_code_eq, i_GP_indiv )


    END DO  ! i

    !---------------------------------------------------------------------------


    ! print the node types if node /= -9999

    !  read the node types from the old  summary file

    DO 

        READ (GP_restart_file_input_unit, '(A)',IOSTAT=istat ) Aline

        IF ( istat /= 0 ) THEN
            exit readloop
        END IF ! istat /=0


        IF ( Aline(1:2) == '> '   ) exit

        READ (Aline, * ) &
             i_GP_Gen, i_GP_indiv,i_tree, i_node, &
             GP_Adult_Population_Node_Type(i_Node,i_Tree,i_GP_indiv)

    END DO



    !---------------------------------------------------------------------------


    ! read all non-zero parameters from the old summary file file

    DO 

        READ (GP_restart_file_input_unit, '(A)',IOSTAT=istat ) Aline
        IF ( istat /= 0 ) THEN
            exit readloop
        END IF ! istat /=0



        IF ( Aline(1:2) == '>>' ) exit

        READ (Aline,*) &
              i_GP_Gen, i_GP_indiv,i_tree, i_node, &
              GP_population_node_parameters( i_node,i_tree, i_GP_indiv)



        !-----------------------------------------------------------------------
        ! add this so that if the restart file has more individuals than the 
        ! run setup, the program will run normally and only take the first
        ! n_GP_individuals

        IF ( i_GP_indiv >= n_GP_individuals ) exit readloop

        !-----------------------------------------------------------------------

    END DO

END DO readloop


!-------------------------------------------------------------------------------


CLOSE ( GP_restart_file_input_unit  )


RETURN


END SUBROUTINE read_all_summary_file
